### ISSUE TITLE
Podspec not linting

### ISSUE THREAD

**Issue by bpoplauschi** [SDWebImage/SDWebImageHEIFCoder#1]
The podspec is not linting and I also get the same error when trying to build the example
- I don't understand why we have the same files in `Vendors/include/libheif` and `Vendors/libheif/libheif` and I mean `heif.h` and `heif-version.h`

```
pod lib lint --allow-warnings --subspec=libheif

 -> SDWebImageHEIFCoder/libheif (0.2.0)
    - ERROR | [SDWebImageHEIFCoder/libheif] public_header_files: The pattern includes header files that are not listed in source_files (/Users/bogdanp/GitHub/SDWebImageHEIFCoder/SDWebImageHEIFCoder/Module/SDWebImageHEIFCoder.h).
    - ERROR | [SDWebImageHEIFCoder/libheif] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [SDWebImageHEIFCoder/libheif] xcodebuild:  /Users/bogdanp/GitHub/SDWebImageHEIFCoder/Vendors/libheif/libheif/heif.h:31:10: fatal error: 'libheif/heif_version.h' file not found
    - NOTE  | [SDWebImageHEIFCoder/libheif] xcodebuild:  /Users/bogdanp/GitHub/SDWebImageHEIFCoder/Vendors/libheif/libheif/heif_plugin.h:28:10: fatal error: 'libheif/heif.h' file not found

[!] SDWebImageHEIFCoder did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.
```

**Comment by dreampiggy** [comment]
@bpoplauschi The submodule `libheif`, that `heif.h` is not a C header files. It's a C header file template for [autoconf](http://www.gnu.org/software/autoconf/). So you can not use it directlly unless you run autoconf for build system (so that you can not use Xcode, good news)

I run the autoconf to generate the final `heif.h`, and replace it. So that we can directlly use git submodule, but not copy their entire source code into this repo :)

I'll check the pod spec lint issue. It may because you don't use `--use-libraries` since there are two embed static library.

**Comment by dreampiggy** [comment]
@bpoplauschi And I want some help. Do you know how to specify in the Podspec, to allow all header be treated as `Project Header` but not `Private Header` or `Public Header` ?

I don't want to add `heif.h`, `de265.h` and `x265.h` into the umbrella header. However, current generated Pods.xcodeproj always assume these files be either `Public Header` or `Private Header`, no way to make it as `Project Header` and pass pob spec lint (I try a trick, works for local but fail on pod lib lint).

Because I create a `modulemap` files with umbrella header. Which should contains all `Public Headers`. Or Xcode will warn you `umbrella header for module 'SDWebImageHEIFCoder' does not include header 'heif.h'`

What I want (works on local Pods, but fail on `pod lib lint` because :`public_header_files: The pattern includes header files that are not listed in source_files`) :

<img width="455" alt="lark20180830-203118" src="https://user-images.githubusercontent.com/6919743/44851677-ac8ea680-ac93-11e8-881c-a4dab6aca957.png">


What I get currentlly that can pass `pod lib lint`:

![image](https://user-images.githubusercontent.com/6919743/44851722-cd56fc00-ac93-11e8-822e-34e3cb17df31.png)

**Comment by dreampiggy** [comment]
@bpoplauschi It seems that `pod lib lint` does not follow what `pod spec lint` do. It does not acutally copy your pod folder like git clone. It just use a soft link to the original files. So the header search path was wrong if you write as this:

`HEADER_SEARCH_PATHS` => `${PODS_ROOT}/SDWebImageHEIFCoder/Vendors/include`
+ `pod lib lint`:  resolve as`/private/var/folders/xxx/CocoaPods-Lint-20180830-30458-1ytwdds-SDWebImageHEIFCoder/Pods/SDWebImageHEIFCoder/Vendors/include`, but however the `Pods/SDWebImageHEIFCoder` folder does not exist. So compile failed.
+ `pod spec lint`:  `Pods/SDWebImageHEIFCoder` does exist. So compile success.

If we still want Travis-CI to pass `pob lib lint`, I have to add a header search path just for developer but not for distributation. Use the `PODS_TARGET_SRCROOT` mentioned in https://github.com/CocoaPods/CocoaPods/issues/7905

You see that this pod is available in CocoaPods trunk, because I always use `pod spec lint` and it pass (Or CocoaPods will reject you to push to trunk)...Maybe it's time to support `pod lib lint`.

**Comment by dreampiggy** [comment]
Done by https://github.com/SDWebImage/SDWebImageHEIFCoder/commit/ef5308af880a841f7bf4f514c0d10e25b3276a67 and CI passed.

Actually this only effect `pod lib lint`, which is for developer. For our user, we always distrbute using pod trunk and it just need to pass `pod spec lint`.

---

Another issue, currentlly I add all `heif.h`, `de265.h`, `x265.h` into the umbrella files, so people who use this module import:

```objectivec
#import <SDWebImageHEIFCoder/SDWebImageHEIFCoder>
@import SDWebImageHEIFCoder;
```

Will see all symbols inside these headers as well, such as `heif_get_version`. I don't know it's suitable to expose this or not. In my opinion, I think that `libde265` && `libx265` should ship as a third-party pods dependency as `libwebp`, but seems that nobody create this.

Acutally I want to hide these headers, but since [umbrella header](https://clang.llvm.org/docs/Modules.html#header-declaration) should contains all public headers (Or Xcode will warn you, can be dismissed as well). I want to find some way to make these header as `Project Header` but not `Public Header`. However, I don't find a good way to do so in podspec syntax, any idea ?

**Comment by dreampiggy** [comment]
Solved by the latest master branch. `pod lib lint` can pass now. Previous version `pod spec lint` is passed (if not, how can I push it to Pod Trunk ? 😅 )
