### ISSUE TITLE
It's too slow

### ISSUE THREAD

**Issue by kaich** [SDWebImage/SDWebImageHEIFCoder#13]
use heif_decode_image to decode a 1.7M image. It take 6 seconds on iPhone 7P. It too slow to decode. Can I make it fast ?

**Comment by dreampiggy** [comment]
@kaich Using Apple Image/IO's for iOS 11+ device. (Just the default `SDImageIOCoder`). This library, it's only used for compatible usage, for user who still at iOS 10...

And, you can try to build your own `libheif` codec, the CocoaPods version: https://cocoapods.org/pods/libheif, I remove the assemble code because of CocoaPods's suck. (Does not support `.s` ASM code). This may improve the performance a little.

**Comment by kaich** [comment]
thanks

**Comment by dreampiggy** [comment]
@kaich Do I need to point this out in Readme ? I've add one, but it's a little Inconspicuous.

Or do I need to update the Example project. To change code like this:

```objective-c
if (@available(iOS 11, macOS 10.13, tvOS 11, *)) {
   // These version supports Image/IO built-in decoding (hardware accelerate for A9+ device)
} else {
   // Don't support HEIF decoding, add coder
    SDImageHEIFCoder *HEIFCoder = [SDImageHEIFCoder sharedCoder];
    [[SDImageCodersManager sharedManager] addCoder:HEIFCoder];
}
```

**Comment by kaich** [comment]
Yes, I think you need point this out in Readme. Or others may think you process this in your code.

**Comment by dreampiggy** [comment]
@kaich Done by 243122b. Including the description and demo code. Refresh GitHub page to show the new readme.
