### ISSUE TITLE
Crash on .heic format images

### ISSUE THREAD

**Issue by visionsIT** [SDWebImage/SDWebImageHEIFCoder#3]
@dreampiggy 
when I have download the image (format .heic) from firebase on real device then  I am getting the crash.
![screenshot 2018-12-11 at 6 43 23 pm](https://user-images.githubusercontent.com/29791900/49803380-9eadee80-fd75-11e8-89a3-d52c352cd18c.png)

**Comment by dreampiggy** [comment]
@visionsIT This seems you're using the default Apple's Image IO decoder (See that `SDWebImageIOCoder.m`). Is that related to this coder plugin ?

This plugin is here to provide lower firmware suppport (iOS 8-iOS 10), which use an open-source libheif decoder, instead of Apple's own close-sourse decoder. If you need to support HEIF in these lower platform, you should use this.

**Comment by dreampiggy** [comment]
@visionsIT Did you try to use this framework ? Firstly read the [Usage](https://github.com/SDWebImage/SDWebImageHEIFCoder#usage) chapter before you face this issue.

You have to add the HEIF coder plugin to plugin manager, and its priority should be higher than the built-in `SDWebImageIOCoder`. But it's also recommended to use SDWebImageIOCoder for iOS 11+ user. So you can write like this.

```objective-c
if (@available(iOS 11.0, *)) {
    // Do nothing
} else {
    SDWebImageAPNGCoder *HEIFCoder = [SDWebImageHEIFCoder sharedCoder];
    [[SDImageCodersManager sharedInstance] addCoder:HEIFCoder];
}
```

After you do that, all HEIF/HEIC image will pass to this decoder instead of that built-in one.

**Comment by dreampiggy** [comment]
@visionsIT Oh. sorry, your code showing you're using the **HEIF encoding** feature ?

For encoding, you should notice that you need subspec `x265` when using this `SDWebImageHEIFCoder` plugin, because it does not use Apple's built-in Image IO framework, including another third-party lib increase the binary size. And most of people don't want to use HEIF encoding.

Your crash log seems strange. What of SDWebImage version did you use ? (We check for HEIF compatibility before usage in that `SDWebImageIOCoder`), so that Apple's Image IO framework should not throw a exception of that `unsupported file format 'public.heic'`.

https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/SDWebImageImageIOCoder.m#L474-L493

**Comment by visionsIT** [comment]
@dreampiggy  i am using SDWebImage  4.4.2

**Comment by dreampiggy** [comment]
@visionsIT Can this reproduceable with some specify HEIF image ? (Please provide the image URL), 

Or is there an iOS hardware && fireware specify issue (for example, only iOS 11.0-beta or only iPhone 6 device face this issue) ?
